// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/car.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CarRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CarId         int32                  `protobuf:"varint,1,opt,name=car_id,json=carId,proto3" json:"car_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CarRequest) Reset() {
	*x = CarRequest{}
	mi := &file_proto_car_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CarRequest) ProtoMessage() {}

func (x *CarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_car_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CarRequest.ProtoReflect.Descriptor instead.
func (*CarRequest) Descriptor() ([]byte, []int) {
	return file_proto_car_proto_rawDescGZIP(), []int{0}
}

func (x *CarRequest) GetCarId() int32 {
	if x != nil {
		return x.CarId
	}
	return 0
}

type CarResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsAvailable   bool                   `protobuf:"varint,1,opt,name=is_available,json=isAvailable,proto3" json:"is_available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CarResponse) Reset() {
	*x = CarResponse{}
	mi := &file_proto_car_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CarResponse) ProtoMessage() {}

func (x *CarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_car_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CarResponse.ProtoReflect.Descriptor instead.
func (*CarResponse) Descriptor() ([]byte, []int) {
	return file_proto_car_proto_rawDescGZIP(), []int{1}
}

func (x *CarResponse) GetIsAvailable() bool {
	if x != nil {
		return x.IsAvailable
	}
	return false
}

var File_proto_car_proto protoreflect.FileDescriptor

const file_proto_car_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/car.proto\x12\x03car\"#\n" +
	"\n" +
	"CarRequest\x12\x15\n" +
	"\x06car_id\x18\x01 \x01(\x05R\x05carId\"0\n" +
	"\vCarResponse\x12!\n" +
	"\fis_available\x18\x01 \x01(\bR\visAvailable2D\n" +
	"\n" +
	"CarService\x126\n" +
	"\x11CheckAvailability\x12\x0f.car.CarRequest\x1a\x10.car.CarResponseB\n" +
	"Z\b./proto/b\x06proto3"

var (
	file_proto_car_proto_rawDescOnce sync.Once
	file_proto_car_proto_rawDescData []byte
)

func file_proto_car_proto_rawDescGZIP() []byte {
	file_proto_car_proto_rawDescOnce.Do(func() {
		file_proto_car_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_car_proto_rawDesc), len(file_proto_car_proto_rawDesc)))
	})
	return file_proto_car_proto_rawDescData
}

var file_proto_car_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_car_proto_goTypes = []any{
	(*CarRequest)(nil),  // 0: car.CarRequest
	(*CarResponse)(nil), // 1: car.CarResponse
}
var file_proto_car_proto_depIdxs = []int32{
	0, // 0: car.CarService.CheckAvailability:input_type -> car.CarRequest
	1, // 1: car.CarService.CheckAvailability:output_type -> car.CarResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_car_proto_init() }
func file_proto_car_proto_init() {
	if File_proto_car_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_car_proto_rawDesc), len(file_proto_car_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_car_proto_goTypes,
		DependencyIndexes: file_proto_car_proto_depIdxs,
		MessageInfos:      file_proto_car_proto_msgTypes,
	}.Build()
	File_proto_car_proto = out.File
	file_proto_car_proto_goTypes = nil
	file_proto_car_proto_depIdxs = nil
}
